### ISSUE TITLE
Comparison to XCB.jl

### ISSUE THREAD

**Issue by serenity4** [MasFlam/XCBased.jl#1]
Hi,

I saw your package being registered in Registry and was curious to know how it compares to [XCB.jl](https://github.com/JuliaGL/XCB.jl)?

**Comment by masflam** [comment]
Hi
I have seen the XCB.jl package before creating this one. The key difference is that this package does not and will not create abstractions around X resources (e.g. windows), but only the functions from XCB. XCB.jl for example introduces a `Window` struct, while my package won't do that – it is focused on wrapping the API functions instead.

**Comment by serenity4** [comment]
I see! Then XCB.jl could rely on XCBased at some point, when it's stable and ready for use.
